-- Move một khách hàng VBSME bị kẹt (đã huỷ nhưng chưa sang bảng _CANCEL)
-- Thay: <SCHEMA> (vd VBSMEONL), <CUSTOMER_ID> (khoá OMNI_CUSTOMER.ID), <CIF> để đối chiếu.
-- Chạy TỪNG câu qua sql_write: gọi KHÔNG token -> nhận preview + confirmation_token -> gọi LẠI kèm token.
-- Token dùng một lần; sửa câu lệnh thì preview lại từ đầu. KHÔNG dùng sql_execute_script.
-- THỨ TỰ BẮT BUỘC: INSERT (customer) -> INSERT (workflow stage) -> VERIFY -> DELETE (stage) -> DELETE (customer).
-- Lý do: đứt giữa 2 bước thì còn bản sao dọn lại được; xoá trước là mất dữ liệu thật.

-- 1) Danh sách cột của 2 bảng để tự tính phần GIAO — OMNI_CUSTOMER_CANCEL thiếu 6 cột:
--    SOTP_EXPIRED_DATE, UNLOCK_TIME, ACTIVE_DATE, LAST_ACTIVE_DATE,
--    NEW_DEVICE_UPDATE_EXPIRED_TIME, BYPASS_EKYC
SELECT TABLE_NAME, LISTAGG(COLUMN_NAME, ',') WITHIN GROUP (ORDER BY COLUMN_ID) AS COLS
FROM SYS.ALL_TAB_COLUMNS
WHERE OWNER = '<SCHEMA>' AND TABLE_NAME IN ('OMNI_CUSTOMER', 'OMNI_CUSTOMER_CANCEL')
GROUP BY TABLE_NAME;

-- 2) Xem trước các dòng con của luồng duyệt sẽ phải mang theo
-- SELECT CUSTOMER_ID, ID, WORKFLOW_STAGE_ID, "LEVEL", WORKFLOW_ID, METHODS, CREATED_BY, CREATED_DATE,
--        MODIFIED_BY, MODIFIED_DATE
-- FROM <SCHEMA>.OMNI_WORKFLOW_STAGE_CUSTOMER WHERE CUSTOMER_ID = <CUSTOMER_ID>;

-- 3) Ghi bản sao khách hàng sang bảng CANCEL — liệt kê đủ cột giao nhau ở CẢ hai vế
-- INSERT INTO <SCHEMA>.OMNI_CUSTOMER_CANCEL (ID,USERNAME,USER_ALIAS,MOBILE_OTT,COMPANY_ID,CIF_NO,...)
--   SELECT ID,USERNAME,USER_ALIAS,MOBILE_OTT,COMPANY_ID,CIF_NO,...
--   FROM <SCHEMA>.OMNI_CUSTOMER WHERE ID = <CUSTOMER_ID>;

-- 4) Ghi bản sao các dòng luồng duyệt (cột LEVEL bọc nháy kép)
-- INSERT INTO <SCHEMA>.OMNI_WORKFLOW_STAGE_CUSTOMER_CANCEL
--   (CUSTOMER_ID,ID,WORKFLOW_STAGE_ID,"LEVEL",CREATED_DATE,MODIFIED_DATE,CREATED_BY,MODIFIED_BY,WORKFLOW_ID,METHODS)
--   SELECT CUSTOMER_ID,ID,WORKFLOW_STAGE_ID,"LEVEL",CREATED_DATE,MODIFIED_DATE,CREATED_BY,MODIFIED_BY,WORKFLOW_ID,METHODS
--   FROM <SCHEMA>.OMNI_WORKFLOW_STAGE_CUSTOMER WHERE CUSTOMER_ID = <CUSTOMER_ID>;

-- 5) VERIFY trước khi xoá: bảng CANCEL đã đủ dòng, bảng gốc vẫn còn nguyên
-- SELECT (SELECT COUNT(*) FROM <SCHEMA>.OMNI_CUSTOMER_CANCEL WHERE ID = <CUSTOMER_ID>) AS IN_CANCEL,
--        (SELECT COUNT(*) FROM <SCHEMA>.OMNI_CUSTOMER WHERE ID = <CUSTOMER_ID>) AS IN_SRC,
--        (SELECT COUNT(*) FROM <SCHEMA>.OMNI_WORKFLOW_STAGE_CUSTOMER_CANCEL WHERE CUSTOMER_ID = <CUSTOMER_ID>) AS WF_IN_CANCEL,
--        (SELECT COUNT(*) FROM <SCHEMA>.OMNI_WORKFLOW_STAGE_CUSTOMER WHERE CUSTOMER_ID = <CUSTOMER_ID>) AS WF_IN_SRC
-- FROM DUAL;

-- 6) XOÁ ở bảng gốc — mỗi câu một token; preview của câu DELETE là bằng chứng ảnh hưởng
-- DELETE FROM <SCHEMA>.OMNI_WORKFLOW_STAGE_CUSTOMER WHERE CUSTOMER_ID = <CUSTOMER_ID>;
-- DELETE FROM <SCHEMA>.OMNI_CUSTOMER WHERE ID = <CUSTOMER_ID>;

-- 7) VERIFY cuối: bảng gốc 0 dòng, bảng CANCEL đủ dòng; soi cùng CIF để chắc không dính user khác
-- SELECT ID, USERNAME, COMPANY_ID, STATUS, PRE_STATUS, OLD_STATUS
-- FROM <SCHEMA>.OMNI_CUSTOMER_CANCEL WHERE CIF_NO = '<CIF>';
